# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('favourite_color', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
            ],
        ),
    ]
