# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework3', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataForm',
            new_name='DataFormModel',
        ),
    ]
